---
title: "第３回高知ユネスコ協会教育シンポジウム"
subtitle: "教員を志す学生から見た子どもたち　～学習習慣をつけるために～"
date: 2025-11-03
author: Yamato Fujii
number-sections: true
---
## 環境による学力変化と教育格差
学力は主に遺伝と環境の２つで決まります。遺伝の影響は大きいですが、環境の影響も無視できません。

経済的に厳しい環境に置かれた子どもたちの学力は、どうしても裕福な環境にある子どもたちより劣る傾向にあります。

Bradbury et al. (2015)など

>親の所得と子どもの学力との相関については、ほぼ全ての国の分析で正の相関がある

樋口・萩原（2017）

>高所得者層の家庭に生まれた子どもは、大人になっても高い所得を得ており、低所得者層の家庭に生まれた子どもは、低い所得しか得られていない。

野崎ほか（2018）

>小学校6年生においては、世帯所得からの影響のうち、学校外教育支出によって媒介される効果が確認
低所得者層への教育支援の充実が子どもの学力向上へ寄与する可能性

これに伴う、**教育格差**の拡大が問題となっています。

我々は、この教育格差の問題を解決するために、日々活動を行っています。

## 講師が見る子どもの教育的課題 ～学習習慣の欠如～
我々が教育現場で感じる子どもの教育的課題として、最も大きく感じるのが、**学習習慣の欠如**です。

### こういう子どもたちが多い
「前回教えたのになあ…」

「家でやるのは宿題だけ」

「もはや宿題すらやらない」　こうなれば家庭学習の時間はゼロ

「定期試験前だけ勉強して普段はやらない」

**非常にもったいない**

### 学習習慣と学力の関係
学習習慣がある子どもは、学力が高い傾向にあります。これは、我々が教育現場で感じるだけでなく、研究でも明らかです。

杉村ほか（1988）

>成績上位群の方が望ましい学習習慣が身についている。
>
>学業成績と学習習慣の関係は学年が進むにつれて強くなる


苅谷（2004）

>学力階層下位の中学生は、自宅でほとんど予習・復習をせず、勉強時間も短い

## 学習習慣の現状








## 引用文献
Bradbery., B, M. Corak, J. Waldfogel, and E. Washbrook. (2015) “Too Many Children Behind The U.S. Achievement Gap in Comparative Perspective.” Russell Sage Foundation, [https://cir.nii.ac.jp/crid/1970304959903771308](https://cir.nii.ac.jp/crid/1970304959903771308)

樋口美雄, 萩原里紗(2017)『大学への教育投資と世代間所得移転：奨学金は救世主か』,勁草書房

野崎華世, 樋口美雄, 中室牧子,妹尾渉(2018)『親の所得・家庭環境と子どもの学力の関係：国際比較を考慮に入れて』, 国立教育政策研究所 NIER Discussion Paper Series No.008, [https://www.nier.go.jp/05_kenkyu_seika/pdf_seika/h28/nier_dps_008_201803.pdf](https://www.nier.go.jp/05_kenkyu_seika/pdf_seika/h28/nier_dps_008_201803.pdf)

杉村健, 井上登世子, 豊田弘司（1988）,『小学生における学習習慣と学業成績の関係』, 奈良教育大学教育研究所紀要 巻 22, p. 43-58 [https://nara-edu.repo.nii.ac.jp/records/9798](https://nara-edu.repo.nii.ac.jp/records/9798)

苅谷剛彦（2000）『学習時間の研究 -努力の不平等とメリトクラシー』，教育社会学研究第66集[https://www.jstage.jst.go.jp/article/eds1951/66/0/66_0_213/_article/-char/ja/](https://www.jstage.jst.go.jp/article/eds1951/66/0/66_0_213/_article/-char/ja/)

高知県HP 令和７年度 全国学力・学習状況調査結果
[https://www.pref.kochi.lg.jp/doc/gakuryokutyousa/file_contents/file_20258144205650_1.pdf](https://www.pref.kochi.lg.jp/doc/gakuryokutyousa/file_contents/file_20258144205650_1.pdf)

国立教育政策研究所『令和６年度経年変化分析調査・保護者に対する調査 』[https://www.nier.go.jp/24chousakekkahoukoku/kannren_chousa/keinen_hogosha_chousa.html](https://www.nier.go.jp/24chousakekkahoukoku/kannren_chousa/keinen_hogosha_chousa.html)

秋田喜代美, 村瀬公胤, 市川洋子（2004）,『中学校入学後の学習習慣の形成過程 -基礎学力を支援する学校・家庭環境の検討-』,東京大学大学院教育学研究科紀要 43巻, 205-234 [https://cir.nii.ac.jp/crid/1390009224602906240](https://cir.nii.ac.jp/crid/1390009224602906240)

豊田弘司（2009）『中学生における学習習慣と学業成績の関係に関する実践的研究』,奈良教育大学教育実践総合センター研究紀要 巻 16, p. 1-6 [https://nara-edu.repo.nii.ac.jp/records/111072025/](https://nara-edu.repo.nii.ac.jp/records/111072025/)

文部科学省『平成29・30・32年度改訂学習指導要領解説』[https://www.mext.go.jp/a_menu/shotou/new-cs/1384661.htm](https://www.mext.go.jp/a_menu/shotou/new-cs/1384661.htm)

高知県教育だより『夢のかけ橋』第102号（令和７年１０月発行）[https://www.pref.kochi.lg.jp/doc/2014061600060/file_contents/file_20251061155652_1.pdf](https://www.pref.kochi.lg.jp/doc/2014061600060/file_contents/file_20251061155652_1.pdf)

荒牧良祐, 浅田 匡（2017）『小学生の学習習慣・学習意識と親の教育観との関係に関する研究』日本教育心理学会第59 回総会発表論文集p.712 [https://www.jstage.jst.go.jp/article/pamjaep/59/0/59_712/_article/-char/ja](https://www.jstage.jst.go.jp/article/pamjaep/59/0/59_712/_article/-char/ja)

志水宏吉, 高田一宏（2016）『マインド・ザ・ギャップ！ ―現代日本の学力格差とその克服―』大阪大学出版