project:
  type: website

website:
  title: "教育のおもちゃ箱 ～やまちゃんのHP～"

  navbar: 
    search: true
    collapse-level: 1
    title: false
    pinned: true
    background: success

    contents:
      - href: index.qmd
        text: Home
        # 他にファイルがあればここに追加
        
      - href: https://yamachan050125.github.io/Syakaika-Siryou/
        text: 授業資料共有サイト「社会科のおもちゃ箱」

 
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

lang: ja
