project:
  type: website

website:
  title: "教育のおもちゃ箱"

  navbar: 
    search: true
    title: false
    pinned: true
    background: success

    left:
      - text: "教育のおもちゃ箱 ～やまちゃんのHP～"
        href: "https://yamachan050125.github.io/"
      - text: "社会科のおもちゃ箱"
        href: "https://yamachan050125.github.io/Syakaika-Siryou/
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

lang: ja
