---
title: "１　平成30年度告示学習指導要領「高校公民 倫理」のポイント"
---

倫理は、**公共科を履修した者のみ**履修が可能である。

<font size="5"> １　目標 </font>

>**人間としての在り方生き方についての見方・考え方を働かせ，現代の諸課題を追究したり解決に向けて構想したりする活動を通して**，広い視野に立ち，人間尊重の精神と生命に対する畏敬の念に基づいて，グローバル化する国際社会に主体的に生きる平和で民主的な国家及び社会の有為な形成者に必要な公民としての資質・能力を次のとおり育成することを目指す。

<font size="4"><font color="red"> 知識・技能 </font>

>（1）古今東西の幅広い知的蓄積を通して，現代の諸課題を捉え，より深く思索するための手掛かりとなる概念や理論について理解するとともに，諸資料から，人間としての在り方生き方に関わる情報を調べまとめる技能を身に付けるようにする。

<font size="4"><font color="green"> 思考力・判断力・表現力等 </font>

>（2）自立した人間として他者と共によりよく生きる自己の生き方についてより深く思索する力や，現代の倫理的諸課題を解決するために倫理に関する概念や理論などを活用して，論理的に思考し，思索を深め，説明したり対話したりする力を養う。

<font size="4"><font color="blue"> 学びに向かう力・人間性等 </font>

>（3）人間としての在り方生き方に関わる事象や課題について主体的に追究したり，他者と共によりよく生きる自己を形成しようとしたりする態度を養うとともに，多面的・多角的な考察やより深い思索を通して涵養される，現代社会に生きる人間としての在り方生き方についての自覚を深める。

倫理において、主な内容は過去の哲学史である。正直かなり量が多い。終わらせるのは不可能である。ただし、公共科により、ある程度の範囲は履修済みであり、すべてを履修する必要はない。



## 倫理の内容構成

<font size="5"> ２　内容 </font>

A 現代に生きる自己の課題と人間としての在り方生き方

>（１）人間としての在り方生き方の自覚人間の存在や価値に関わる基本的な課題について思索する活動を通して，次の事項を身に付けることができるよう指導する。（略）
>
>（２）国際社会に生きる日本人としての自覚過去や他所の様々な人々の生き方や考え方を参考に…日本人としての在り方生き方について思索する活動を通して，次の事項を身に付けることができるよう指導する。（略）

ここで、今後の思考過程で重要となる**知識・技能**を習得する。

<font color="red">この過去や他所の様々な人々の生き方や考え方を参考に...</font>

B 現代の諸課題と倫理

>（１）自然や科学技術に関わる諸課題と倫理
>
>自然や科学技術とのかかわりにおいて，人間としての在り方生き方についての見方・考え方を働かせ，他者と対話しながら，現代の諸課題を探究する活動を通して，次の事項を身に付けることができるよう指導する。（略）
>
>（２）社会と文化に関わる諸課題と倫理
>
>関連させる今の社会の課題について自ら考える様々な他者との協働，共生に向けて，人間としての在り方生き方についての見方・考え方を働かせ，他者と対話しながら，現代の諸課題を探究する活動を通して，次の事項を身に付けることができるよう指導する。（略）

<font color="red">現在の社会的課題について、自ら考える</font>

::: {.callout-important}
# 重要
Aで先人の知識を学び、Bで現在の社会的課題を解決する
:::

## 道徳科との関連

高等学校においては、道徳化が存在しない。
それを補っているのが、**公民の倫理分野**である。

道徳教育は，教育基本法及び学校教育法に定められた教育の根本精神に基づき，生徒が自己探求と自己実現に努め国家・社会の一員としての自覚に基づき行為しうる発達の段階にあることを考慮し，<font color="red">人間としての在り方生き方</font>を考え，主体的な判断の下に行動し，自立した人間として他者と共によりよく生きるための基盤となる道徳性を養うことを目標とすること。

道徳教育を進めるに当たっては，<font color="red">人間尊重の精神と生命に対する畏敬の念</font>を家庭，学校，その他社会における具体的な生活の中に生かし，豊かな心をもち，伝統と文化を尊重し，それらを育んできた我が国と郷土を愛し，個性豊かな文化の創造を図るとともに，平和で民主的な国家及び社会の形成者として，公共の精神を尊び，社会及び国家の発展に努め，他国を尊重し，国際社会の平和と発展や環境の保全に貢献し未来を拓く主体性のある日本人の育成に資することとなるよう特に留意すること。




