---
title: "２　哲学的思考と高校倫理の難しさ"
---
## 哲学的思考

哲学の判断基準は、**合理的か否か**である。

## 合理的判断とは？
合理的判断に必要な要素は３つ

1. **事実と価値の区別**
   
   「～である」は事実、「～であるべき」は価値
   
   事実判断から価値判断は**直に**出ない。
   
   :::{.callout-warning}
   ## 注意
   Ex）「昔から牛を使っている」（事実）

    　　　　　　　↓
   
   「牛を利用してよい」（価値）
   
    この論理の持って生き方は**合理的ではない**。
   :::

2. **判断の一貫性**
   
   道徳的に重要な違いがない限り、全てにおいて一貫性がある。

3. **公平な視点**
   
   自己中心的ではなくて、普遍な判断をする。
   ただし、普遍性を極めすぎても、ほかの面と両立しなくなるので難しい…

## 高校倫理を教える難しさ

### 政経部門とちがい、教科書や資料集を読んでもよくわからない
   
   高校倫理を教えるうえで、上記の哲学的思考は、生徒が身に着けるべき思考法である。しかしながら、哲学的思考はとても難しく、高校生どころか大人でも難しい。
   
   哲学者の思考は、すべてこの思考法に基づいているわけであるが、この思考法を失念してしまうと、ただでさえ難しい文章が理解不能な文章と化す。教員も、この思考法は失念しがちであり、生徒ともに哲学の泥沼へハマっていく。

   そうして**暗記中心**の活動になっていき、**倫理の内容が多すぎる**こともあり、適切な思考力を養成できない場合が多い。

### 「課題・問題ベース」と「思想史ベース」の兼ね合いがむずかしい
   
   「主体的・対話的・深い学び」が目標であるにもかかわらず、内容は**思想史が中心**になってしまう。**基礎的な概念や理論の把握がないと対話の効果は限定的だと思うけど、そうした把握をさせているだけで時間が溶けていく**。

### 抽象的な話になるので、生徒の関心を維持できない
「具体」⇔「抽象」が大事な気がするが難しい。そもそも何が（哲学的に）問題なのか理解させにくいことがあるほか、具体的な問題には関心を引けても、それについての抽象的考察まで関心を維持しにくい。

### reason（理性・理由）への信頼

   往々にして哲学は「理性・理由」を重視する。そのため、「感覚としては受けいれがたいが理性・理由に従うとこうならざるをえない」という議論もある。これを学ぶ際にどのようにして付き合うのか。


## 高校倫理と学問の倫理学の違い

|分野|内容|
|--|--|
|倫理学|Ethics　学問としての倫理学　善/悪,　正/不正を探求|
|高校倫理|哲学史の要素強め　暗記（最近は脱暗記傾向）|

## 高校倫理の授業における映画の活用
* 抽象的なものが具体化できるので、理解しやすい
* 例示と理論の間の誤差を学ぶことができる（逆効果になることも？）
* ディティールが議論の邪魔になる恐れ（中高生はそっちへ行きがち）
* メモ取らせたり、時間に気を使わないと、睡眠導入剤になる

これは、適切な発問やワークシートでカバーする必要がある

