---
title: "３　客観主義と主観主義"
---

# メタ倫理学

規範倫理学で前提とされている事柄を一段上から（＝メタに）研究すること

* 倫理に答えはあるのか？
* 倫理の事柄は普遍的であるのか？
* 倫理的な判断とは何か？
* 倫理的な判断は動機づけの力を持つか？

**根本を問う**学問分野

:::{.callout-note}
## 例） イスラム圏での女性の教育差別
イスラムの文化では、女性は教育において差別される。しかし、彼らの文化では正しい価値観であり、それをほかの国の文化の目線から批判することは許されるのか？
:::

#### 倫理学の問いに答えはない？
**倫理学の問いに「答えはないのではない」というのは、証明できていない。** そうではなくて、**答えを出すのが難しい**ということはわかる。

## 客観主義

「リンゴは丸いのはなぜ？」という問いは「丸い」という**客観的な性質**を持つから言える。

→ 「良さ」なども客観的性質があるという考え方

#### 客観性
  * 「善さ」を普遍的なものだと考えられる
  * ある行為が善いのは、実際にその行為が善いからであって、それは当の行為を見てみればだれにでもわかる
  
  * つまり、誰がどう見ても正しいという概念が生まれる

#### 安定性・確実性
  * 善さも対象側に変化がない限り、安定している

#### 可謬性
  * 私たちは、道徳的進歩を認められる

### 客観主義への批判
* 道徳的性質は客観的か？（味のように、私たち主観の側が投影しているだけでは…）
* 仮に客観的な善さや正しさがあったとしても、一体それが誰にどうやってわかるの？

## 主観主義

#### 差異の説明
  * 倫理的な判断の個人差を説明できる　「人それぞれ」

#### 認識論的に優位

#### 倫理の身分
  * 倫理的な価値は「私たちのものだ」といえる。
  * 倫理のために人間があるわけではなく、人間のために倫理があるのではないか？

### 主観主義への批判
* 奴隷制や男尊女卑を肯定する道徳観も「人それぞれ」で成立する
* 外部からの批判ができないので、倫理は権力者や多数派のものになってしまう
* 大悪人を批判することはできなくなる

## 道徳的相対主義
道徳的な事柄が当てはまるかどうかは、文化や社会によって変わるという考え方

:::{.callout-note}
## 例
死者への弔い方も火葬・土葬・死者の肉を食らうなど様々で、それが正しいかは文化で異なる
:::
   

### 反論
* （例に対して）周辺信念が違うだけで、死者を弔う気持ちは一緒なら道徳は同じであろう
* 事実として違っていても道徳的に批判ができなくなる
  * Ex）地球平面説は科学で否定できるが、道徳的観点から批判不可能



