---
title: "４　功利主義と義務論"
---

# 規範倫理学
行為の **「正・不正」の基準** を扱う分野

「私たちはどのように行為すべきか？」

以下の考え方が対立

1. **帰結主義**：正・不正の基準は「帰結」にある
2. **義務論**：正・不正の基準は「義務」にある
3. **徳倫理学**：正・不正の基準は「徳」にある (今回は扱わず)

# 功利主義

:::{.callout-note}
## 功利性の原理
行為の正・不正の基準は帰結であり、関係者の幸福を最大化するような行為を選択すべし。（最大多数の最大幸福）
:::

1. **帰結主義**：結果よければすべてよし
2. **福利主義** ：人々の幸福/不幸で決めるべき（快楽/苦痛や選考充足で決める）
3. **単純加算主義** ：得られた関係者の幸福は、全員の幸福を単純加算することでランク付けされる（功利主義における公平性や平等性を担保する部分）
4. **最大化** ：ある一群の選択肢が与えられたとき、望ましさの高い選択肢を選ぶべき

### 功利主義のメリット
* 功利主義はシンプルかつ整合的で、適用範囲も広い。
* またモラルジレンマに一義的な回答を与えられる。

### 功利主義と利己主義の違い
よく混同されるので注意

:::{.callout-note}
## 功利主義
**自分も他人も** 幸福になる道を目指そう
:::

winwinを目指すのが功利主義。なので、たまに自己犠牲を要求される。

:::{.callout-note}
## 利己主義
**他人より自分が** 幸福になる道を探そう
:::

#### 功利主義への批判

* どうやって幸福を比較する？
  
  →**厚生経済学**の考えを使えば、お金に換算できる
* 快楽＝幸福？
  
  快楽を望まない場合があるのではないか
  
> Nozick, 1974,「経験機械」
> 
> あなたが望む経験をなんでも与えてくれる経験機械なるものがあるとしよう。超一流の神経心理学者であれば、あなたの脳を刺激することで、偉大な小説を書いたり、友達をつくったり、おもしろい本を読んだりしているとあなたに考えさせたり感じさせたりできるだろう。そのあいだずっと、あなたは脳に電極をつけた状態でタンクのなかに浮かんでいることになる。さて、あなたはじぶんの人生の経験をすべて事前にプログラムして、一生この機械に繋がれていたいだろうか。

「快楽」は主観的な心の状態。

* 直観に反する行為が許容されてしまう。大勢のために一人が犠牲になる場合がある。
  * この問題は、 選好充足の考え方で解決可能

### 選好充足
いくつかの選択肢が与えられたときに、そのあいだでつけられる序列

* 選好された選択肢が実現すれば「幸福」

  ➡「幸福」と「望むこと」のギャップはない！

* 「充足」は「心理的な充実感」ではなく、現実に果たされたかどうか（心の状態より見通しやすい）
* じつは個人が経験しなくともOK（e. g. 遺言）

#### 選好充足の問題点

1. **適応的選好形成**
   
   人は、環境で適応する形で選好を決める。つまり、環境によって、本人の選好は制限されている。その状況では、例えば、人権を知らないひとが人権を欲しいと言うわけがない。

2. **選択自体が選好に影響を与える場合**
   
   洗脳の前には洗脳を選好していなかったが、洗脳後には選好するようになってしまった……？


3. **直観に反する行為が許容**
   
これに対応するために、義務論の考えを組み込みながら、理論をパワーアップ

### 規則功利主義
   
   功利的な判断の対象は行為ではなく**規則**。規則の採択の時に功利判断を下し、行為の時に幸福計算を不要にする。

:::{.callout-note}   
## 例
「約束を守る」という規則を採択して、ここの行為の選択場面では、当該の規則に絶対的に従う。
:::
絶対的にというところに義務論要素を取り入れている。

  **問題点** 
    
   * 功利主義としてあり？
     * 個別の場面で明らかに不幸になる人が大勢いたとしても規則には絶対順守しなければならない
   * 本当に義務の絶対性は認められるのか？
     * その義務はどうして絶対といえるのか
  
### 二層理論
   
   現代では、もっとも洗練されている功利主義。道徳的な思考のレベルを二つに分ける。
   
1. 直感的レベル
   
単純な直観的規則に絶対的に従う。功利計算はコストが高く、バイアスがかかるので、日常では直観に従う方がよい

2. 批判的レベル

例外的な状態において、個々の行為に個別的に功利計算する。計算するまでもなく、直観的にまずそうな行為や、直観同士がぶつかるものの場合、功利計算をすること。

この２つを柔軟に行き来できることが大切

### 功利主義を使って、義務を扱う
   
 「嘘をつくな」という義務は、「従えば**たいてい**幸福」という経験則に基づくといえる。

 問題は「たいてい」というところ。幸福計算ができない。


# 義務論
功利主義の対抗馬。
行為の正・不正の基準は「義務」にかなっているかによって決まる。

:::{.callout-note}
## 義務論
帰結とは関係なく、行為自体が正しいか正しくないか
:::

### カントの考え方
カントが求めるのは **「無条件に善いもの」＝「善意志」**（功利主義では幸福）

> 我々が無条件に善とみとめうるものとしては、この世界の内にもまた外にも、ただ善なる意志しか考えられない。

行為の正当性は意志にある。**正しい行為とは、たまたま義務にかなっている行為ではなく、義務に基づく行為が正しい。**

例えば…

    Ex）人を助けるときにどうすべきか

   1. お金や名声のために助ける（適法的）
   2. そうすべきだから助ける（道徳的）

このような時、カントの言う善意志は、2になる。
意志が義務に基づくのは、**道徳法則への純粋な尊敬に働き動かされるとき**。私たちは理性を持つが、感性も持つ。**感性に打ち勝ち、義務に基づく行為をすべき**。

**人格**＝道徳的な行為をする者

弱い人間は常に道徳法則にしたがうわけではない。

→人間にとって、道徳法則は「命法」（命令形）という姿で提示される。

:::{.callout-note}
## 仮言命法
「○○なら××せよ」　条件付き
:::

:::{.callout-note}
## 定言命法
××せよという無条件の命法
:::

**道徳法則は、普遍性を持つので、定言命法**

### 道徳法則の性質
道徳法則は３つ性質がある

#### **第一定式**
  
  > 汝の確立が、普遍的法則となることを汝が同時にその格率によって意志しうる場合にのみ、その格率に従って行為せよ。

  **行為の主観的規則**
  
  格率を普遍化したときに、うまくできるなら、それは道徳法則にかなう。

#### **第二定式**
  
  > 汝の人格の中にも、ほかのすべての人の人格のなかにもある人間性を、汝がいつも同時に目的として用い、決して**単に**手段として**のみ**用いない、というようなふうに行為せよ。
  
  カントは「物件」と「人格」を区別する。
    
    物件：理性を持たず、目的のための手段。「価格」が備わる。

    人格：理性を持ち、それ自体が目的となる。「理性」が備わる。

  要は、**人をモノ扱いしちゃダメ**という考え方

  ただし、「単に」手段として「のみ」なので、**相手が認めない目的のために利用するのはダメ**というだけであり、相手の合意があればOK

#### **第三定式**
  
  > 意志がその格率によって自己自身を同時に普遍的立法者ともみなしうるようなしかたでのみ行為せよ。

  自分自身を「普遍的立法者」とみなす＝**自律**

  →自らの行為の法則を自ら立て、それに従う。

  自分のことは自分で決める＝**自由**

## 問題点
* 義務は**絶対的で無条件**であり、いかなるときも嘘をついてはならない。
  
  → いい嘘に対しては…？カントは、道徳法則を捻じ曲げてまですることではないと説明する。

* **モラルジレンマ**の対応ができない
  
  → カントは、**完全義務**と**不完全義務**を区別し、義務の間に序列を作ることで対処。ただ、序列付けは難しくね？という反論もある。

### 義務論のメリット
* 何をすればいいのかわかりやすく計算不要
* 不公平や権利侵害が起こり得ない
  * 大勢のために一人を犠牲にすることは認められない
* **行為者相対性**がある

### 義務論のデメリット
* モラルジレンマに対応しにくい
* 義務があらかじめ定まっていない場合は？
  * 脳死などの新しい状況が科学の発達で発生
* 既存の義務そのものの妥当性は？
  * 「女は専業主婦になるべき」みたいなものは理不尽

## 功利主義 vs 義務論
Ex）トロリー問題

トロリーが暴走している。このままでは５人が縛り付けられているところへ向かう。もう片方には１人縛り付けられている。あなたはトロリーの進路を変えるか
