---
title: "５　社会契約説"
---

|中世（キリスト教カトリック時代）|絶対王政（**王権神授説**）|
|:--:|:--:|
|神＞教皇＞国王|神＞国王|

中世のカトリックが支配する時代では、教皇の方が国王より上になる。(例：**聖職叙任権**)

しかし、十字軍失敗などでカトリックの教皇の権威は失墜。絶対王政が発生し、**王権神授説**がでて、王が一番上へ。

しかし、王に抑圧された民衆が反乱を起こす（フランス革命など）。ここで出てきたのが、社会契約説である。

## 契約とは
1. 一神教において
   
    神　→契約→　人間
    
2. 社会契約
   
   神と人間は平等である

# 社会契約説とは

:::{.callout-note}
## 社会契約説
自由で平等な個人が自らの意思によって契約を結び、国家権力を創出する。
:::

**自然法**：神によって定められた普遍的な法則。これを理性によって読み解く。
この自然法を保証するのが、**自然権**

**自然権**：神が人に与えた権利＝人の生得的な権利　↔実定法による権利（人が人に与えた権利）

国家権力は、この自然権を前提として国家権力を創造する。

 > 社会状態　←（契約）←　自然状態（問題あり）

## 社会契約説の画期性
1. 国家権力の根拠を神から人へ

    |王権神授説|社会契約説|
    |--|--|
    |神が国王に王権を授与。国王が神の信任の元に民を支配|神が規定した民が王と契約を結ぶことで、民の信任の元、自然権を王に預ける|
  
    国王を契約制にするという発想

2. 科学的手法によるアプローチ
   
   **原子論**

   社会契約説は原子論の応用。社会契約説は、社会の単位は個人になる。原子のように、社会の最小構成単位は分割できないので、ここから政治哲学も考えてよいのではないかという発想から生まれている。**国王も民も人間なのだから、最小単位は一緒。つまり、出自なども考える必要性はない。**

## ホップズ「リバイアサン」
表紙が有名

王の体は、人でできている。多くの人から国王が成り立っているということを示す

### ホップズの考える自然状態

> 万人の万人による闘争

人間の最高の目的は「**自己保存**」

### ホップズの自然権

> 自らの生命を維持するための権利

### ホップズの自然法

> 生命が脅かされることを禁ずる

### ホップズの特徴
* 人々が自らの権利を権力者に**譲渡**
  * 平和と安全に関する権力者の意思や判断（＝法）に服従する
  * 絶対王政的であるが、これはピューリタン革命のように**強い権力を持たせないと内政が崩壊する**と考えていたから

## ロック「統治二論」
### ロックの自然状態

> 自由で平等、自然法に拘束される

自然に労働を加えることで、必要なものを生産する

### ロックの自然権
1. **所有権/固有権**
2. **処罰権**
   * ヒトは自然状態において、プロパティの侵害に対して、**各自が処罰する権利を持つ**。
    
      →これ結構危なくね？

    > 自然状態には問題がある。だから **契約を結ぼう！** という考え方

    ホップズと違うのは、自然権を**譲渡**ではなく**貸与**している点にある

### 革命権
   * 人々に信託に基づき国家は成立するので、目的に反する場合、信託は失効し、権力は人々の手に戻る
   * その場合は、革命という形で政府を破壊しても構わない
   * 日本では、「**内閣不信任決議**」という形で規定

## ルソー　「社会契約論」

ルソーは、ロックなどよりだいぶ後に出てきた人物。
ホップズとロックの自然状態を批判。

2人と違い、**自然状態のほうが望ましい**という。
自然人は、**所有権という概念がなく、自由で平等**だから。

しかし、人間は農耕を始めるなど、不自由で不平等の社会状態を始めようとする。

> 不平等な社会状態を**契約によって自由平等な社会状態に変えよう**とする考え方

→　この手段が**革命**であり、その結果、フランス革命が発生