---
title: "６　応用倫理学と生命倫理学"
---
# 応用倫理学
応用倫理学は、**規範倫理学の成果を個別の場面に応用すること**であり、**新技術の発達に伴い、新しい問題が生まれることから、理論の修正などが行われる。**

従来の倫理学の人間観　＝　「**理性的存在者**」
　根本のモデルは、**成熟した理性的**な**白人**の**男性**

## 伝統的な人間観の更新
医療現場にはこの前提から外れている人もいる。（乳幼児、重度の知的障害、脳死など）彼らは我々は人間として扱う。であれば、従来の原理には限界。

理性中心主義によって、健全な理性を持つ者以外の人間が排除され始めた。

# 生命倫理学
## 4つの基本原則
1. **自立尊重原理**
   
   選択は患者がする
2. **無危害原理**
   
   患者が安楽死を望んでも、決して患者を殺したり傷つけたりしてはならない
3. **仁恵原理**
   
   患者にとって良いとみなせる治療を（手術拒否を説得するなど）
4. **正義原理**
   
   貧しい人も治療を受けられるように医療資源の配分は公平にせよ

**パターナリズム（家父長主義）**
：医者の言うことには従え　今はNG

**インフォームドコンセント**
：患者が治療方針を十分説明し、患者の意思を確認し、患者が選択する

## 脳死問題
### 医学上の死の取り扱い
1. 呼吸停止
2. 心拍停止
3. 瞳孔散大

→ 人工呼吸器の登場で、「脳死」という概念が登場

### 脳死の規定
1. 人間の基本的動き（意識や感覚）を維持
2. 身体の統合（呼吸や心拍機能）

**脳死は、この２機能の喪失**と定義

:::{.callout-warning}
## 植物状態
植物状態は１であり、長期の生存・回復があり得る
:::

### 脳死は人の死か？
脳の二機能が失われるなら、医学的・生物学的には、もはや「生」ではない？

- 脳死で「個体としての統一性」が失われる？
  - 脳死患者は出産がありうる
- 脳死状態になったら数日中に心停止に至る？
  - 14年ほど生きる長期脳死もありうる

とはいえ、日本でも法整備が進む。


|1997 臓器移植法|2010 改正臓器移植法|
|--|--|
|本人の書面による意思表示(書面)| 本人の意思が不明の場合、家族の同意で移植可能|
|家族の承認が必要||
|15歳未満提供不可|年齢制限なし|
||親族への優先提供|


### 懸念点
* ドナー側
  * ドナー側の意思が尊重されているか。
  * 周囲から近親者に圧力がかからないか
* レシピエント側
  * 臓器移植は最良の治療法になっているか？
  * 免疫の問題
    - 移植後は免疫抑制剤の投与を続ける必要（＝ 抵抗力の低下）
  * 精神的負担


## 再生医療
再生医療は、事故や病気で損傷した部位を再び再生させる。

ただし倫理的問題が絡んでくることも

### 幹細胞
特定の組織や臓器になる手前にあり、失われた細胞を再生産して補充する能力をもった細胞

1. **多分化能**
   
   さまざまな細胞に分化する能力

2. **自己複製能**
   
   じぶんとまったく同じ能力をもつ細胞に分裂する能力

幹細胞には、**細胞幹細胞**と**多能性幹細胞**が存在し、多能性幹細胞は、胎盤などを除くあらゆる細胞に分化する能力を持つ。

Ex）iPS細胞　ES細胞

## 人胚の道徳的地位
### ES細胞
「胚性幹細胞（ES細胞）」は、**受精卵**からの成長過程の細胞からつくられる幹細胞
- 受精卵に非常に近い胚の細胞からつくられるので、あらゆる細胞に分化しうる「万能細胞」
- iPS細胞が出てくるまでは再生医療の中心だった

### ES細胞の問題点
1. **患者本人の細胞ではないので拒絶反応のリスクがある**
   * 通常のES細胞ベースの移植で拒絶反応が生じるのは、それが他人の細胞だから
   
    ➡ じゃあ、患者本人の細胞からつくればよいのでは？
   
    ＝ **「ヒト・クローン胚」からのES細胞作製**

    そうした「ヒト・クローン胚」は、そのまま育てば「クローン人間」になる……
    
    ➡ **どこかしらで胚が盗まれてクローンがつくられるという可能性もなくはない（禁断）**


2. **ヒトES細胞は受精卵を「破壊」してつくられる**
   * 一方で「生命尊重主義」からすれば、**いずれ人間になるヒト胚を手段として “殺害する” ことはNG**
   * たとえばカトリックは受精の瞬間から「生命」と認めるため、大反対している
  
     ➡「ヒト胚も生きる権利をもつ」
  
#### これに対する反論
  * 通常の妊娠過程でもひとりの子どもが生まれるまでに1~4つの受精卵が “死んで” いる ➡ 生命尊重主義は立場を一貫できるか？
  * ヒト胚は潜在的に人格をもつ？
    *  一般に潜在的にXだからといって現時点でXとしての権利をもつわけではない


## クローニング
問題点は３つ
1. **クローンによって人間の尊厳がおびやかされる**
2. **同じ遺伝子をもつ人間が複数存在することで個体性があいまいになる**
   
#### 反論

* 「一卵性双生児」は自然なクローンとも云えるものだが、それによって尊厳や個体性は損なわれていない（むしろ一卵性双生児の方が、年齢は同じだし、生育環境も同じになりがちなので、類似性は高いはず）
   
   クローニングは人間の「道具化」か？（cf. カント～義務論）

* 私たちはさまざまな目的で子どもを設ける（老後のため、男の子／女の子がほしい etc.）
  
  ➡ そういった（ありふれた）事例も「道具化」にあたる？


1. **人類の遺伝子プールが画一化し、環境の変化（疫病など）に耐えられなくなるのでは？**
  
   **反論**
   
   * いまから2,000年前には人口も遥かに少なかったので、人類の遺伝子プールの多様性も遥かに少なかったはず
    
    ➡ それでも問題なかったのだからよいのでは？
   
   * そこまでクローニングが一般化することはあるのか？
  
     とはいえ、じぶんの遺伝子をもった子どもを設ける方法がクローンしかないという状況も想定しうる。

## iPS細胞
京大　山中伸弥教授開発

>受精卵を用いず患者本人の体細胞から作製できる
＝ **拒絶反応もないし、ヒト・クローン胚の破壊もない**

ただし、ただし、現時点ではシャーレの上で十分な臓器を作製することはできない

➡ ブタなどの動物の身体を借りる必要がある……